/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem {
  'name' : string,
  'restaurantId' : RestaurantId,
  'quantity' : bigint,
  'price' : bigint,
  'menuItemId' : MenuItemId,
}
export type CuisineType = { 'other' : string } |
  { 'mediterranean' : null } |
  { 'thai' : null } |
  { 'japanese' : null } |
  { 'chinese' : null } |
  { 'mexican' : null } |
  { 'fastFood' : null } |
  { 'italian' : null } |
  { 'indian' : null } |
  { 'american' : null };
export interface MenuItem {
  'id' : MenuItemId,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'restaurantId' : RestaurantId,
  'imageUrl' : string,
  'category' : string,
  'price' : bigint,
}
export type MenuItemId = bigint;
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'deliveryAddress' : string,
  'deliveryFee' : bigint,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'estimatedDeliveryMinutes' : bigint,
  'restaurantId' : RestaurantId,
  'updatedAt' : Timestamp,
  'specialInstructions' : string,
  'totalAmount' : bigint,
  'restaurantName' : string,
  'items' : Array<CartItem>,
}
export type OrderId = bigint;
export type OrderStatus = { 'preparing' : null } |
  { 'cancelled' : null } |
  { 'onTheWay' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface PlaceOrderRequest {
  'deliveryAddress' : string,
  'restaurantId' : RestaurantId,
  'specialInstructions' : string,
  'items' : Array<CartItem>,
}
export interface Restaurant {
  'id' : RestaurantId,
  'deliveryFee' : bigint,
  'name' : string,
  'estimatedDeliveryMinutes' : bigint,
  'cuisineType' : CuisineType,
  'description' : string,
  'isOpen' : boolean,
  'imageUrl' : string,
  'rating' : bigint,
}
export type RestaurantId = bigint;
export interface SavedAddress { 'tag' : string, 'address' : string }
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'createdAt' : Timestamp,
  'savedAddresses' : Array<SavedAddress>,
}
export interface _SERVICE {
  'getMenuItem' : ActorMethod<[MenuItemId], [] | [MenuItem]>,
  'getMenuItems' : ActorMethod<[RestaurantId], Array<MenuItem>>,
  'getMyProfile' : ActorMethod<[], UserProfile>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getRestaurant' : ActorMethod<[RestaurantId], [] | [Restaurant]>,
  'getUserOrders' : ActorMethod<[], Array<Order>>,
  'listRestaurants' : ActorMethod<[], Array<Restaurant>>,
  'placeOrder' : ActorMethod<[PlaceOrderRequest], Order>,
  'removeAddress' : ActorMethod<[string], undefined>,
  'reorder' : ActorMethod<[OrderId, string], [] | [Order]>,
  'saveAddress' : ActorMethod<[SavedAddress], undefined>,
  'searchRestaurants' : ActorMethod<
    [string, [] | [CuisineType], [] | [bigint]],
    Array<Restaurant>
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];