/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MenuItemId = IDL.Nat;
export const RestaurantId = IDL.Nat;
export const MenuItem = IDL.Record({
  'id' : MenuItemId,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'restaurantId' : RestaurantId,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const SavedAddress = IDL.Record({
  'tag' : IDL.Text,
  'address' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'createdAt' : Timestamp,
  'savedAddresses' : IDL.Vec(SavedAddress),
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'preparing' : IDL.Null,
  'cancelled' : IDL.Null,
  'onTheWay' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const CartItem = IDL.Record({
  'name' : IDL.Text,
  'restaurantId' : RestaurantId,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
  'menuItemId' : MenuItemId,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'deliveryAddress' : IDL.Text,
  'deliveryFee' : IDL.Nat,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'estimatedDeliveryMinutes' : IDL.Nat,
  'restaurantId' : RestaurantId,
  'updatedAt' : Timestamp,
  'specialInstructions' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'restaurantName' : IDL.Text,
  'items' : IDL.Vec(CartItem),
});
export const CuisineType = IDL.Variant({
  'other' : IDL.Text,
  'mediterranean' : IDL.Null,
  'thai' : IDL.Null,
  'japanese' : IDL.Null,
  'chinese' : IDL.Null,
  'mexican' : IDL.Null,
  'fastFood' : IDL.Null,
  'italian' : IDL.Null,
  'indian' : IDL.Null,
  'american' : IDL.Null,
});
export const Restaurant = IDL.Record({
  'id' : RestaurantId,
  'deliveryFee' : IDL.Nat,
  'name' : IDL.Text,
  'estimatedDeliveryMinutes' : IDL.Nat,
  'cuisineType' : CuisineType,
  'description' : IDL.Text,
  'isOpen' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'rating' : IDL.Nat,
});
export const PlaceOrderRequest = IDL.Record({
  'deliveryAddress' : IDL.Text,
  'restaurantId' : RestaurantId,
  'specialInstructions' : IDL.Text,
  'items' : IDL.Vec(CartItem),
});

export const idlService = IDL.Service({
  'getMenuItem' : IDL.Func([MenuItemId], [IDL.Opt(MenuItem)], ['query']),
  'getMenuItems' : IDL.Func([RestaurantId], [IDL.Vec(MenuItem)], ['query']),
  'getMyProfile' : IDL.Func([], [UserProfile], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getRestaurant' : IDL.Func([RestaurantId], [IDL.Opt(Restaurant)], ['query']),
  'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
  'placeOrder' : IDL.Func([PlaceOrderRequest], [Order], []),
  'removeAddress' : IDL.Func([IDL.Text], [], []),
  'reorder' : IDL.Func([OrderId, IDL.Text], [IDL.Opt(Order)], []),
  'saveAddress' : IDL.Func([SavedAddress], [], []),
  'searchRestaurants' : IDL.Func(
      [IDL.Text, IDL.Opt(CuisineType), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Restaurant)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MenuItemId = IDL.Nat;
  const RestaurantId = IDL.Nat;
  const MenuItem = IDL.Record({
    'id' : MenuItemId,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'restaurantId' : RestaurantId,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const SavedAddress = IDL.Record({ 'tag' : IDL.Text, 'address' : IDL.Text });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'createdAt' : Timestamp,
    'savedAddresses' : IDL.Vec(SavedAddress),
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'preparing' : IDL.Null,
    'cancelled' : IDL.Null,
    'onTheWay' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const CartItem = IDL.Record({
    'name' : IDL.Text,
    'restaurantId' : RestaurantId,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
    'menuItemId' : MenuItemId,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'deliveryAddress' : IDL.Text,
    'deliveryFee' : IDL.Nat,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'estimatedDeliveryMinutes' : IDL.Nat,
    'restaurantId' : RestaurantId,
    'updatedAt' : Timestamp,
    'specialInstructions' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'restaurantName' : IDL.Text,
    'items' : IDL.Vec(CartItem),
  });
  const CuisineType = IDL.Variant({
    'other' : IDL.Text,
    'mediterranean' : IDL.Null,
    'thai' : IDL.Null,
    'japanese' : IDL.Null,
    'chinese' : IDL.Null,
    'mexican' : IDL.Null,
    'fastFood' : IDL.Null,
    'italian' : IDL.Null,
    'indian' : IDL.Null,
    'american' : IDL.Null,
  });
  const Restaurant = IDL.Record({
    'id' : RestaurantId,
    'deliveryFee' : IDL.Nat,
    'name' : IDL.Text,
    'estimatedDeliveryMinutes' : IDL.Nat,
    'cuisineType' : CuisineType,
    'description' : IDL.Text,
    'isOpen' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const PlaceOrderRequest = IDL.Record({
    'deliveryAddress' : IDL.Text,
    'restaurantId' : RestaurantId,
    'specialInstructions' : IDL.Text,
    'items' : IDL.Vec(CartItem),
  });
  
  return IDL.Service({
    'getMenuItem' : IDL.Func([MenuItemId], [IDL.Opt(MenuItem)], ['query']),
    'getMenuItems' : IDL.Func([RestaurantId], [IDL.Vec(MenuItem)], ['query']),
    'getMyProfile' : IDL.Func([], [UserProfile], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getRestaurant' : IDL.Func(
        [RestaurantId],
        [IDL.Opt(Restaurant)],
        ['query'],
      ),
    'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
    'placeOrder' : IDL.Func([PlaceOrderRequest], [Order], []),
    'removeAddress' : IDL.Func([IDL.Text], [], []),
    'reorder' : IDL.Func([OrderId, IDL.Text], [IDL.Opt(Order)], []),
    'saveAddress' : IDL.Func([SavedAddress], [], []),
    'searchRestaurants' : IDL.Func(
        [IDL.Text, IDL.Opt(CuisineType), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Restaurant)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };