/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PlaceOrderRequest {
    deliveryAddress: string;
    restaurantId: RestaurantId;
    specialInstructions: string;
    items: Array<CartItem>;
}
export type Timestamp = bigint;
export type CuisineType = {
    __kind__: "other";
    other: string;
} | {
    __kind__: "mediterranean";
    mediterranean: null;
} | {
    __kind__: "thai";
    thai: null;
} | {
    __kind__: "japanese";
    japanese: null;
} | {
    __kind__: "chinese";
    chinese: null;
} | {
    __kind__: "mexican";
    mexican: null;
} | {
    __kind__: "fastFood";
    fastFood: null;
} | {
    __kind__: "italian";
    italian: null;
} | {
    __kind__: "indian";
    indian: null;
} | {
    __kind__: "american";
    american: null;
};
export type RestaurantId = bigint;
export interface Order {
    id: OrderId;
    status: OrderStatus;
    deliveryAddress: string;
    deliveryFee: bigint;
    userId: UserId;
    createdAt: Timestamp;
    estimatedDeliveryMinutes: bigint;
    restaurantId: RestaurantId;
    updatedAt: Timestamp;
    specialInstructions: string;
    totalAmount: bigint;
    restaurantName: string;
    items: Array<CartItem>;
}
export interface Restaurant {
    id: RestaurantId;
    deliveryFee: bigint;
    name: string;
    estimatedDeliveryMinutes: bigint;
    cuisineType: CuisineType;
    description: string;
    isOpen: boolean;
    imageUrl: string;
    rating: bigint;
}
export interface SavedAddress {
    tag: string;
    address: string;
}
export type UserId = Principal;
export type MenuItemId = bigint;
export interface MenuItem {
    id: MenuItemId;
    name: string;
    isAvailable: boolean;
    description: string;
    restaurantId: RestaurantId;
    imageUrl: string;
    category: string;
    price: bigint;
}
export interface CartItem {
    name: string;
    restaurantId: RestaurantId;
    quantity: bigint;
    price: bigint;
    menuItemId: MenuItemId;
}
export interface UserProfile {
    id: UserId;
    createdAt: Timestamp;
    savedAddresses: Array<SavedAddress>;
}
export type OrderId = bigint;
export enum OrderStatus {
    preparing = "preparing",
    cancelled = "cancelled",
    onTheWay = "onTheWay",
    delivered = "delivered",
    confirmed = "confirmed"
}
export interface backendInterface {
    getMenuItem(id: MenuItemId): Promise<MenuItem | null>;
    getMenuItems(restaurantId: RestaurantId): Promise<Array<MenuItem>>;
    getMyProfile(): Promise<UserProfile>;
    getOrder(orderId: OrderId): Promise<Order | null>;
    getRestaurant(id: RestaurantId): Promise<Restaurant | null>;
    getUserOrders(): Promise<Array<Order>>;
    listRestaurants(): Promise<Array<Restaurant>>;
    placeOrder(req: PlaceOrderRequest): Promise<Order>;
    removeAddress(addressTag: string): Promise<void>;
    reorder(originalOrderId: OrderId, deliveryAddress: string): Promise<Order | null>;
    saveAddress(address: SavedAddress): Promise<void>;
    searchRestaurants(nameQuery: string, cuisineFilter: CuisineType | null, minRating: bigint | null): Promise<Array<Restaurant>>;
}
import type { CartItem as _CartItem, CuisineType as _CuisineType, MenuItem as _MenuItem, Order as _Order, OrderId as _OrderId, OrderStatus as _OrderStatus, Restaurant as _Restaurant, RestaurantId as _RestaurantId, Timestamp as _Timestamp, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getMenuItem(arg0: MenuItemId): Promise<MenuItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItem(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItem(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMenuItems(arg0: RestaurantId): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItems(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItems(arg0);
            return result;
        }
    }
    async getMyProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return result;
        }
    }
    async getOrder(arg0: OrderId): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRestaurant(arg0: RestaurantId): Promise<Restaurant | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRestaurant(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRestaurant(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserOrders();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserOrders();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async listRestaurants(): Promise<Array<Restaurant>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRestaurants();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRestaurants();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async placeOrder(arg0: PlaceOrderRequest): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0);
                return from_candid_Order_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0);
            return from_candid_Order_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeAddress(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAddress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAddress(arg0);
            return result;
        }
    }
    async reorder(arg0: OrderId, arg1: string): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.reorder(arg0, arg1);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorder(arg0, arg1);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveAddress(arg0: SavedAddress): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAddress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAddress(arg0);
            return result;
        }
    }
    async searchRestaurants(arg0: string, arg1: CuisineType | null, arg2: bigint | null): Promise<Array<Restaurant>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchRestaurants(arg0, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchRestaurants(arg0, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CuisineType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CuisineType): CuisineType {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Restaurant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Restaurant): Restaurant {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MenuItem]): MenuItem | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Restaurant]): Restaurant | null {
    return value.length === 0 ? null : from_candid_Restaurant_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    status: _OrderStatus;
    deliveryAddress: string;
    deliveryFee: bigint;
    userId: _UserId;
    createdAt: _Timestamp;
    estimatedDeliveryMinutes: bigint;
    restaurantId: _RestaurantId;
    updatedAt: _Timestamp;
    specialInstructions: string;
    totalAmount: bigint;
    restaurantName: string;
    items: Array<_CartItem>;
}): {
    id: OrderId;
    status: OrderStatus;
    deliveryAddress: string;
    deliveryFee: bigint;
    userId: UserId;
    createdAt: Timestamp;
    estimatedDeliveryMinutes: bigint;
    restaurantId: RestaurantId;
    updatedAt: Timestamp;
    specialInstructions: string;
    totalAmount: bigint;
    restaurantName: string;
    items: Array<CartItem>;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n5(_uploadFile, _downloadFile, value.status),
        deliveryAddress: value.deliveryAddress,
        deliveryFee: value.deliveryFee,
        userId: value.userId,
        createdAt: value.createdAt,
        estimatedDeliveryMinutes: value.estimatedDeliveryMinutes,
        restaurantId: value.restaurantId,
        updatedAt: value.updatedAt,
        specialInstructions: value.specialInstructions,
        totalAmount: value.totalAmount,
        restaurantName: value.restaurantName,
        items: value.items
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RestaurantId;
    deliveryFee: bigint;
    name: string;
    estimatedDeliveryMinutes: bigint;
    cuisineType: _CuisineType;
    description: string;
    isOpen: boolean;
    imageUrl: string;
    rating: bigint;
}): {
    id: RestaurantId;
    deliveryFee: bigint;
    name: string;
    estimatedDeliveryMinutes: bigint;
    cuisineType: CuisineType;
    description: string;
    isOpen: boolean;
    imageUrl: string;
    rating: bigint;
} {
    return {
        id: value.id,
        deliveryFee: value.deliveryFee,
        name: value.name,
        estimatedDeliveryMinutes: value.estimatedDeliveryMinutes,
        cuisineType: from_candid_CuisineType_n10(_uploadFile, _downloadFile, value.cuisineType),
        description: value.description,
        isOpen: value.isOpen,
        imageUrl: value.imageUrl,
        rating: value.rating
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: string;
} | {
    mediterranean: null;
} | {
    thai: null;
} | {
    japanese: null;
} | {
    chinese: null;
} | {
    mexican: null;
} | {
    fastFood: null;
} | {
    italian: null;
} | {
    indian: null;
} | {
    american: null;
}): {
    __kind__: "other";
    other: string;
} | {
    __kind__: "mediterranean";
    mediterranean: null;
} | {
    __kind__: "thai";
    thai: null;
} | {
    __kind__: "japanese";
    japanese: null;
} | {
    __kind__: "chinese";
    chinese: null;
} | {
    __kind__: "mexican";
    mexican: null;
} | {
    __kind__: "fastFood";
    fastFood: null;
} | {
    __kind__: "italian";
    italian: null;
} | {
    __kind__: "indian";
    indian: null;
} | {
    __kind__: "american";
    american: null;
} {
    return "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "mediterranean" in value ? {
        __kind__: "mediterranean",
        mediterranean: value.mediterranean
    } : "thai" in value ? {
        __kind__: "thai",
        thai: value.thai
    } : "japanese" in value ? {
        __kind__: "japanese",
        japanese: value.japanese
    } : "chinese" in value ? {
        __kind__: "chinese",
        chinese: value.chinese
    } : "mexican" in value ? {
        __kind__: "mexican",
        mexican: value.mexican
    } : "fastFood" in value ? {
        __kind__: "fastFood",
        fastFood: value.fastFood
    } : "italian" in value ? {
        __kind__: "italian",
        italian: value.italian
    } : "indian" in value ? {
        __kind__: "indian",
        indian: value.indian
    } : "american" in value ? {
        __kind__: "american",
        american: value.american
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    preparing: null;
} | {
    cancelled: null;
} | {
    onTheWay: null;
} | {
    delivered: null;
} | {
    confirmed: null;
}): OrderStatus {
    return "preparing" in value ? OrderStatus.preparing : "cancelled" in value ? OrderStatus.cancelled : "onTheWay" in value ? OrderStatus.onTheWay : "delivered" in value ? OrderStatus.delivered : "confirmed" in value ? OrderStatus.confirmed : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Restaurant>): Array<Restaurant> {
    return value.map((x)=>from_candid_Restaurant_n8(_uploadFile, _downloadFile, x));
}
function to_candid_CuisineType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CuisineType): _CuisineType {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CuisineType | null): [] | [_CuisineType] {
    return value === null ? candid_none() : candid_some(to_candid_CuisineType_n15(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "other";
    other: string;
} | {
    __kind__: "mediterranean";
    mediterranean: null;
} | {
    __kind__: "thai";
    thai: null;
} | {
    __kind__: "japanese";
    japanese: null;
} | {
    __kind__: "chinese";
    chinese: null;
} | {
    __kind__: "mexican";
    mexican: null;
} | {
    __kind__: "fastFood";
    fastFood: null;
} | {
    __kind__: "italian";
    italian: null;
} | {
    __kind__: "indian";
    indian: null;
} | {
    __kind__: "american";
    american: null;
}): {
    other: string;
} | {
    mediterranean: null;
} | {
    thai: null;
} | {
    japanese: null;
} | {
    chinese: null;
} | {
    mexican: null;
} | {
    fastFood: null;
} | {
    italian: null;
} | {
    indian: null;
} | {
    american: null;
} {
    return value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "mediterranean" ? {
        mediterranean: value.mediterranean
    } : value.__kind__ === "thai" ? {
        thai: value.thai
    } : value.__kind__ === "japanese" ? {
        japanese: value.japanese
    } : value.__kind__ === "chinese" ? {
        chinese: value.chinese
    } : value.__kind__ === "mexican" ? {
        mexican: value.mexican
    } : value.__kind__ === "fastFood" ? {
        fastFood: value.fastFood
    } : value.__kind__ === "italian" ? {
        italian: value.italian
    } : value.__kind__ === "indian" ? {
        indian: value.indian
    } : value.__kind__ === "american" ? {
        american: value.american
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
